# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lekker' do
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  pod 'react-native-video', :path => '../node_modules/react-native-video'

end
